version: '2'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    # TODO: Change hard-coded port to a port read from the env file
    ports:
      - "8080:8080"
    environment:
      # Fixes hot reload when using Windows/Mac. An explanation:
      #
      # https://daten-und-bass.io/blog/enabling-hot-reloading-with-vuejs-and-vue-cli-in-docker/
      #
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/src
  rosbridge:
    build:
      context: .
      dockerfile: ros2_ws/src/rosbridge/Dockerfile
    ports:
      - "9090:9090"
  planner:
    build:
      context: .
      dockerfile: ros2_ws/src/planner/Dockerfile
  neuronavigation:
    build:
      context: .
      dockerfile: ros2_ws/src/neuronavigation_pkg/Dockerfile
    environment:
      - DISPLAY=130.233.100.240:0.0
  efield:
    build:
      context: .
      dockerfile: ros2_ws/src/efield/Dockerfile
