version: '3.8'

services:
  eeg_simulator:
    image: okahilak/mtms:eeg_simulator
    environment:
      - EEG_SIMULATOR_DATA_FILE_NAME=/app/ros2_ws/src/eeg_simulator/oscillation_data.csv
      - EEG_SIMULATOR_SAMPLING_FREQUENCY=50.0
      - ROS_LOG_LEVEL=info
    volumes:
      - './ros2_ws/src/eeg_simulator:/app/ros2_ws/src/eeg_simulator/'
      - './ros2_ws/src/mtms_interfaces:/app/ros2_ws/src/mtms_interfaces/'
      - './oscillation_data.csv:/app/ros2_ws/src/eeg_simulator/oscillation_data.csv'
    deploy:
      placement:
        constraints:
          - node.role == manager


  data_batcher_wrapper:
    image: docker
    command: docker run --privileged --net=weavenet --env ROS_LOG_LEVEL --env DATA_BATCHER_BATCH_SIZE --env DATA_BATCHER_DOWNSAMPLE_RATIO okahilak/mtms:data_batcher
    # --env-file=/app/ros2_ws/.env
    environment:
      - ROS_LOG_LEVEL=info
      - DATA_BATCHER_BATCH_SIZE=100
      - DATA_BATCHER_DOWNSAMPLE_RATIO=10
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      # - './.env:/app/ros2_ws/.env'
    deploy:
      placement:
        constraints:
          - node.role == worker

networks:
  default:
    driver: weaveworks/net-plugin:latest_release
    attachable: true
    name: weavenet
    driver_opts:
      works.weave.multicast: "true"
