version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: front/Dockerfile.prod

  rosbridge:
    build:
      context: .
      dockerfile: ros2_ws/src/rosbridge/Dockerfile

  eeg_simulator:
    build:
      context: .
      dockerfile: ros2_ws/src/eeg_simulator/Dockerfile

  data_batcher:
    build:
      context: .
      dockerfile: ros2_ws/src/data_batcher/Dockerfile

  neuronavigation:
    build:
      context: .
      dockerfile: ros2_ws/src/neuronavigation_pkg/Dockerfile
    env_file:
      - ${ENV_FILE}

  registry:
    image: registry
    ports:
      - target: 5000
        published: 5000
        mode: host