version: '2'

services:
  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './front:/app'
      - '/app/node_modules'

  rosbridge:
    build:
      context: .
      dockerfile: ros2_ws/src/bridges/rosbridge/Dockerfile
    ports:
      - "9090:9090"
    network_mode: host

  eeg_gatherer:
    build:
      context: .
      dockerfile: ros2_ws/src/eeg/eeg_gatherer/Dockerfile
    env_file:
      - ${ENV_FILE}
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: "host"

  eeg_simulator:
    build:
      context: .
      dockerfile: ros2_ws/src/eeg/eeg_simulator/Dockerfile
    env_file:
      - ${ENV_FILE}
    # this option is needed for the container to achieve the same performance as without docker. Optionally, also
    # privileged: true can be used
    security_opt:
      - seccomp:unconfined
    volumes:
      - './ros2_ws/src/eeg/eeg_simulator:/app/ros2_ws/src/eeg/eeg_simulator/'
      - './oscillation_data.csv:/app/ros2_ws/src/eeg/eeg_simulator/oscillation_data.csv'

  eeg_preprocessor:
    build:
      context: .
      dockerfile: ros2_ws/src/eeg/eeg_processor/Dockerfile
    entrypoint: 'bash /app/ros2_ws/preprocessor_ros_entrypoint.sh'
    env_file:
      - ${ENV_FILE}
    volumes:
      - './hotswappable_processors:/app/ros2_ws/hotswappable_processors/'
      - './measurements:/app/ros2_ws/measurements'
    # The container needs to be privileged to set real-time priority.
    privileged: true

  eeg_processor:
    build:
      context: .
      dockerfile: ros2_ws/src/eeg/eeg_processor/Dockerfile
    env_file:
      - ${ENV_FILE}
    volumes:
      - './hotswappable_processors:/app/ros2_ws/hotswappable_processors/'
      - './measurements:/app/ros2_ws/measurements'
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: host

  eeg_bridge:
    ports:
      - "50000:50000/udp"
    build:
      context: .
      dockerfile: ros2_ws/src/bridges/eeg_bridge/Dockerfile
    env_file:
      - ${ENV_FILE}
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: "host"

  mtms_device_bridge:
    build:
      context: .
      dockerfile: ros2_ws/src/bridges/mtms_device_bridge/Dockerfile
    # The container needs to be privileged to access FPGA.
    privileged: true
    env_file:
      - ${ENV_FILE}

  eeg_batcher:
    build:
      context: .
      dockerfile: ros2_ws/src/eeg/eeg_batcher/Dockerfile
    env_file:
      - ${ENV_FILE}
    privileged: true

  planner:
    build:
      context: .
      dockerfile: ros2_ws/src/ui/planner/Dockerfile
    env_file:
      - ${ENV_FILE}
    volumes:
      - './ros2_ws/src/ui/planner:/app/ros2_ws/src/ui/planner/'

  pulse_sequence_controller:
    build:
      context: .
      dockerfile: ros2_ws/src/ui/pulse_sequence_controller/Dockerfile
    env_file:
      - ${ENV_FILE}
    volumes:
      - './ros2_ws/src/ui/pulse_sequence_controller:/app/ros2_ws/src/ui/pulse_sequence_controller/'

  neuronavigation:
    build:
      context: .
      dockerfile: ros2_ws/src/neuronavigation/neuronavigation/Dockerfile
    env_file:
      - ${ENV_FILE}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - './data/neuronavigation:/app/data/neuronavigation/'
    # Required by Linux when opening projects in neuronavigation, otherwise segfaults.
    privileged: true
    network_mode: host

  efield:
    build:
      context: .
      dockerfile: ros2_ws/src/targeting/efield/Dockerfile
    env_file:
      - ${ENV_FILE}
    volumes:
      - './data/neuronavigation/efield:/app/ros2_ws/src/targeting/efield/efield_libraries/data/headmodels/invesalius'
    network_mode: host
   
  optitrack_bridge:
    build:
      context: .
      dockerfile: ros2_ws/src/bridges/optitrack_bridge/Dockerfile
    network_mode: host
    env_file:
      - ${ENV_FILE}

  pedal_listener:
    build:
      context: .
      dockerfile: ros2_ws/src/other/pedal_listener/Dockerfile
    # The container needs to be privileged so that /dev devices (namely, the USB pedal) are created.
    privileged: true
    env_file:
      - ${ENV_FILE}

  stimulus_presenter:
    build:
      context: .
      dockerfile: ros2_ws/src/eeg/eeg_processor/Dockerfile
    entrypoint: 'bash /app/ros2_ws/stimulus_presenter_ros_entrypoint.sh'
    env_file:
      - ${ENV_FILE}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - './hotswappable_processors:/app/ros2_ws/hotswappable_processors/'
      - './measurements:/app/ros2_ws/measurements'
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: host

  targeting:
    build:
      context: .
      dockerfile: ros2_ws/src/targeting/targeting/Dockerfile
    env_file:
      - ${ENV_FILE}
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: "host"

  topic_frequency:
    build:
      context: .
      dockerfile: ros2_ws/src/other/topic_frequency/Dockerfile
    env_file:
      - ${ENV_FILE}
    privileged: true

  trigger_controller:
    build:
      context: .
      dockerfile: ros2_ws/src/other/trigger_controller/Dockerfile
    # The container needs to be privileged so that /dev devices (namely, the trigger USB device) are created.
    privileged: true
    env_file:
      - ${ENV_FILE}

  waveforms:
    build:
      context: .
      dockerfile: ros2_ws/src/targeting/waveforms/Dockerfile
    env_file:
      - ${ENV_FILE}
    network_mode: "host"
