version: '2'

services:

  eeg_preprocessor:
    build:
      context: .
      dockerfile: ros2_ws/src/eeg/eeg_processor/Dockerfile
    entrypoint: 'bash /app/eeg_preprocessor_entrypoint.sh'
    env_file:
      - ${SITE_ENV_FILE}
      - ${PROJECT_ENV_FILE}
    environment:
      - PROJECT_DIR=/app/projects/$PROJECT_NAME/
    volumes:
      - '$PROJECTS_ROOT:/app/projects'
      - './pipeline:/app/pipeline/'
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: host

  eeg_processor:
    build:
      context: .
      dockerfile: ros2_ws/src/eeg/eeg_processor/Dockerfile
    env_file:
      - ${SITE_ENV_FILE}
      - ${PROJECT_ENV_FILE}
    environment:
      - PROJECT_DIR=/app/projects/$PROJECT_NAME/
    volumes:
      - '$PROJECTS_ROOT:/app/projects'
      - './pipeline:/app/pipeline/'
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: host

  stimulus_presenter:
    build:
      context: .
      dockerfile: ros2_ws/src/eeg/eeg_processor/Dockerfile
    entrypoint: 'bash /app/stimulus_presenter_entrypoint.sh'
    env_file:
      - ${SITE_ENV_FILE}
      - ${PROJECT_ENV_FILE}
    environment:
      - DISPLAY
      - PROJECT_DIR=/app/projects/$PROJECT_NAME/
    volumes:
      - '$PROJECTS_ROOT:/app/projects'
      - './pipeline:/app/pipeline/'
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: host
