version: '2'

services:
  # This service simulates the user and its interactions with the system.
  tester:
    build:
      context: .
      dockerfile: py/integration_tests/Dockerfile
    depends_on:
      - backend
    env_file:
      - ${ENV_FILE}
    volumes:
      - ./py/integration_tests:/code/py/integration_tests
    networks:
      - backend
