version: '2'

services:
  efield:
    build:
      context: .
      dockerfile: ros2_ws/src/mtms_packages/targeting/efield/Dockerfile.cuda2
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - './data/neuronavigation:/app/data/neuronavigation/'
    network_mode: host
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mtms_device_bridge:
    build:
      context: .
      dockerfile: ros2_ws/src/mtms_packages/mtms/mtms_device_bridge/Dockerfile
    # The container needs to be privileged to access FPGA.
    privileged: true
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host

  mtms_simulator:
    build:
      context: .
      dockerfile: ros2_ws/src/mtms_packages/simulators/mtms_simulator/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host

  neuronavigation:
    build:
      context: .
      dockerfile: ros2_ws/src/mtms_packages/neuronavigation/neuronavigation/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - DISPLAY
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - './data/neuronavigation:/app/data/neuronavigation/'
      # Mount the configuration to local filesystem so that it is retained when the container is restarted.
      - './.config/invesalius:/root/.config/invesalius'

    # Required by Linux when opening projects in neuronavigation, otherwise segfaults.
    privileged: true
    network_mode: host

  optitrack_bridge:
    build:
      context: .
      dockerfile: ros2_ws/src/mtms_packages/scratch/optitrack_bridge/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host

  planner:
    build:
      context: .
      dockerfile: ros2_ws/src/mtms_packages/ui/planner/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - './ros2_ws/src/mtms_packages/ui/planner:/app/ros2_ws/src/mtms_packages/ui/planner/'
    network_mode: host
