version: '3.5'

services:
  planner_test:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/mtms_packages/ui/planner/Dockerfile

networks:
  cinetwork:
    name: cinetwork
    driver: bridge