# Maximum number of pulse pieces
uint16 maximum_number_of_pulse_pieces

# Maximum pulse duration, in ticks
uint16 maximum_pulse_duration_ticks

# Maximum time difference between rising and falling phases of pulse, in ticks
uint16 maximum_rising_falling_difference_ticks

# Maximum pulses per time unit; the maximum pulses.
uint8 pulses_in_maximum_pulses_per_time

# Maximum pulses per time unit; the time unit in milliseconds.
uint16 time_in_maximum_pulses_per_time_ms
