#!/bin/bash

# Get the site from the first argument
SITE="$1"

if [ -z "$SITE" ]; then
    echo "Error: Site is undefined. Please provide it as an argument to the script."
    echo ""
    exit 1
fi

# Set the site in .bashrc
if ! grep -q "export SITE=$SITE" ~/.bashrc; then
    echo "export SITE=$SITE" >> ~/.bashrc
fi

# Add environment variable to .bashrc, pointing to repository root
if ! grep -q 'export MTMS_ROOT=/home/mtms/mtms' ~/.bashrc; then
    echo 'export MTMS_ROOT=/home/mtms/mtms' >> ~/.bashrc
fi

# Set the site environment variable in .bashrc
if ! grep -q 'export SITE_ENV_FILE=$MTMS_ROOT/sites/$SITE/.env' ~/.bashrc; then
    echo 'export SITE_ENV_FILE=$MTMS_ROOT/sites/$SITE/.env' >> ~/.bashrc
fi

# Add environment variable to .bashrc, pointing to projects directory
if ! grep -q 'export PROJECTS_ROOT=/home/mtms/projects' ~/.bashrc; then
    echo 'export PROJECTS_ROOT=/home/mtms/projects' >> ~/.bashrc
fi

# Add environment variable to .bashrc to configure ROS to use Cyclone DDS
if ! grep -q 'export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp' ~/.bashrc; then
    echo 'export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp' >> ~/.bashrc
fi

# Add environment variable to .bashrc to configure DDS
if ! grep -q 'export CYCLONEDDS_URI=file://$MTMS_ROOT/config/cyclonedds.xml' ~/.bashrc; then
    echo 'export CYCLONEDDS_URI=file://$MTMS_ROOT/config/cyclonedds.xml' >> ~/.bashrc
fi

# Add ROS sourcing to .bashrc unless it is already there
if ! grep -q 'source /opt/ros/iron/setup.bash' ~/.bashrc; then
    echo 'source /opt/ros/iron/setup.bash' >> ~/.bashrc
fi

# Add sourcing of ROS packages to .bashrc
if ! grep -q 'source $MTMS_ROOT/ros2_ws/install/local_setup.bash' ~/.bashrc; then
    echo 'source $MTMS_ROOT/ros2_ws/install/local_setup.bash' >> ~/.bashrc
fi

# Add path to Python API to PYTHONPATH
if ! grep -q 'export PYTHONPATH=$MTMS_ROOT/api/python:$PYTHONPATH' ~/.bashrc; then
    echo 'export PYTHONPATH=$MTMS_ROOT/api/python:$PYTHONPATH' >> ~/.bashrc
fi

# Add script directory to path in .bashrc
if ! grep -q 'export PATH=$PATH:$MTMS_ROOT/scripts/linux/usage' ~/.bashrc; then
    echo 'export PATH=$PATH:$MTMS_ROOT/scripts/linux/usage' >> ~/.bashrc
fi

# Needed for custom ROS messages to work in MATLAB.
if ! grep -q 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6' ~/.bashrc; then
    echo 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6' >> ~/.bashrc
fi

# Needed for custom Python 3.9.5 installation to work in MATLAB.
if ! grep -q 'export LD_LIBRARY_PATH=/opt/python3.9.5/lib:$LD_LIBRARY_PATH' ~/.bashrc; then
    echo 'export LD_LIBRARY_PATH=/opt/python3.9.5/lib:$LD_LIBRARY_PATH' >> ~/.bashrc
fi

# Automatically show instructions when opening a new terminal
if ! grep -q 'instructions' ~/.bashrc; then
    echo 'instructions' >> ~/.bashrc
fi
