#!/bin/bash

source install-docker.sh
source install-ros.sh

# Install Cyclone DDS for ROS
sudo apt install -y ros-humble-rmw-cyclonedds-cpp

# Tools for troubleshooting
sudo apt install -y net-tools wireshark

# Tools for customizing GNOME (not required)
sudo apt install wmctrl

# Add environment variable to .bashrc, pointing to repository root
if ! grep -q "export MTMS_ROOT=/home/mtms/mtms" ~/.bashrc; then
    echo "export MTMS_ROOT=/home/mtms/mtms" >> ~/.bashrc
fi

# Add ROS sourcing to .bashrc unless it is already there
if ! grep -q "source /opt/ros/humble/setup.bash" ~/.bashrc; then
    echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
fi

if ! grep -q "source $MTMS_ROOT/ros2_ws/install/local_setup.bash" ~/.bashrc; then
    echo 'source $MTMS_ROOT/ros2_ws/install/local_setup.bash' >> ~/.bashrc
fi

# Add environment variable to .bashrc to configure ROS to use Cyclone DDS
if ! grep -q "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" ~/.bashrc; then
    echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" >> ~/.bashrc
fi

# Add path to Python API to PYTHONPATH
if ! grep -q "export PYTHONPATH=$MTMS_ROOT/api/python:$PYTHONPATH" ~/.bashrc; then
    echo 'export PYTHONPATH=$MTMS_ROOT/api/python:$PYTHONPATH' >> ~/.bashrc
fi

# Add script directory to path in .bashrc
if ! grep -q "export PATH=$PATH:$MTMS_ROOT/scripts/linux/usage" ~/.bashrc; then
    echo 'export PATH=$PATH:$MTMS_ROOT/scripts/linux/usage' >> ~/.bashrc
fi
