FROM osrf/ros:iron-desktop@sha256:eddad5f79aa7e888af29793c11f0ee44280c656b74dba0d37b2f48a0aa57352e

SHELL ["/bin/bash", "-c"]

# Install dependencies

RUN apt-get update && \
    apt-get install -y \
    dos2unix \
    python3-pip \
    wget \
    tar \
    ros-iron-rmw-cyclonedds-cpp && \
    rm -rf /var/lib/apt/lists/*

# Download and install LabJack LJM
RUN wget https://files.labjack.com/installers/LJM/Linux/x64/release/labjack_ljm_software_2019_07_16_x86_64.tar.gz && \
    tar -zvxf labjack_ljm_software_2019_07_16_x86_64.tar.gz && \
    cd labjack_ljm_software_2019_07_16_x86_64 && \
    # XXX: The LJM installer fails with error code 127 when run in Docker container, possibly related to the part
    #   installing device rules. LabJack can still be accessed and used, but it doesn't work over reconnects without
    #   a workaround (mapping /dev in local Ubuntu into the /dev of the container, see docker-compose.yml for a more
    #   detailed explanation.)
    sudo bash -x ./labjack_ljm_installer.run || true && \
    cd .. && \
    rm -rf labjack_ljm_software_2019_07_16_x86_64 labjack_ljm_software_2019_07_16_x86_64.tar.gz

# Set the Cyclone DDS configuration
COPY config/cyclonedds.xml /config/
ENV CYCLONEDDS_URI=file:///config/cyclonedds.xml

# Copy ROS workspace and build packages

WORKDIR /app/ros2_ws

# ROS interfaces
COPY ros2_ws/src/interfaces/event_interfaces src/interfaces/event_interfaces/
COPY ros2_ws/src/interfaces/system_interfaces src/interfaces/system_interfaces/
RUN source /opt/ros/iron/setup.bash && colcon build

# ROS node
COPY ros2_ws/src/pipeline/triggerer src/pipeline/triggerer/
RUN source /opt/ros/iron/setup.bash && colcon build --symlink-install --packages-select triggerer

# Copy entrypoint

WORKDIR /app

COPY ros2_ws/src/pipeline/triggerer/ros_entrypoint.sh .
RUN dos2unix ros_entrypoint.sh
RUN chmod +x ros_entrypoint.sh

ENTRYPOINT ["./ros_entrypoint.sh"]
