version: '3.5'

services:
  planner:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/ui/planner/Dockerfile

  pulse_sequence_controller:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/ui/pulse_sequence_controller/Dockerfile

  neuronavigation:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/neuronavigation/neuronavigation/Dockerfile

  efield:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/targeting/efield/Dockerfile

  pedal_listener:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/other/pedal_listener/Dockerfile

  trigger_controller:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/other/trigger_controller/Dockerfile

  eeg_simulator:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/eeg/eeg_simulator/Dockerfile

  eeg_processor:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/eeg/eeg_processor/Dockerfile

  eeg_bridge:
    networks:
      - cinetwork
    ports:
      - "50000:50000/udp"
    build:
      context: ..
      dockerfile: ros2_ws/src/bridges/eeg_bridge/Dockerfile

  mtms_device_bridge:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/bridges/mtms_device_bridge/Dockerfile

  data_batcher:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/eeg/data_batcher/Dockerfile

  optitrack_bridge:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/bridges/optitrack_bridge/Dockerfile

  targeting:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/targeting/targeting/Dockerfile

  waveforms:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/targeting/waveforms/Dockerfile

networks:
  cinetwork:
    name: cinetwork
    driver: bridge
