version: '3.5'

services:
  front_test:
    build: ../front/
    networks:
      - cinetwork
    ports:
      - "3000:3000"
    depends_on:
      - rosbridge_test
      - planner_test
      - pulse_sequence_controller_test
  rosbridge_test:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/rosbridge/Dockerfile
    ports:
      - "9090:9090"
  planner_test:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/planner/Dockerfile
  pulse_sequence_controller_test:
    networks:
      - cinetwork
    build:
      context: ..
      dockerfile: ros2_ws/src/pulse_sequence_controller/Dockerfile

networks:
  cinetwork:
    name: cinetwork
    driver: bridge