#!/bin/bash

# Define the text formatting codes
BOLD=$(tput bold)
RESET=$(tput sgr0)

# Check that the project name is set.
if [ -z "$PROJECT_NAME" ]; then
    echo "Error: Project name is undefined. Please use set-project script to set the project."
    echo ""
    exit 1
fi

code $MTMS_ROOT/projects/$PROJECT_NAME/.env

echo ""
echo "Start system by running: ${BOLD}start-mtms${RESET}"
echo ""
