#!/bin/bash

# Define the text formatting codes
BOLD=$(tput bold)
RESET=$(tput sgr0)

# Get the project name from the first argument
PROJECT_NAME="$1"

if [ -z "$PROJECT_NAME" ]; then
    echo "Error: Project name is undefined. Please provide it as an argument to the script."
    echo ""
    exit 1
fi

# Check if the project directory exists
if [ -d "$PROJECTS_ROOT/$PROJECT_NAME" ]; then
    echo "Error: Project already exists: ${BOLD}$PROJECT_NAME${RESET}"
    echo ""
    exit 1
fi

mkdir $PROJECTS_ROOT/$PROJECT_NAME
cp $MTMS_ROOT/.env $PROJECTS_ROOT/$PROJECT_NAME

echo ""
echo "Project successfully created: ${BOLD}$PROJECT_NAME${RESET}"
echo ""
