#!/bin/bash

# Set the path to the projects directory
PROJECT_DIR="$MTMS_ROOT/projects"

# Get a list of all directories inside the projects directory
PROJECT_DIRS=$(find "$PROJECT_DIR" -maxdepth 1 -type d ! -name 'projects')

echo ""
echo "Available projects:"

# Loop through each project directory and print its name
for dir in $PROJECT_DIRS; do
    echo "  $(basename $dir)"
done

echo ""
echo "Set project by running:"
echo ""
echo "source set-project [project-name]"
echo ""
