#!/bin/bash

# Check that SITE_ENV_FILE is set.
if [ -z "$SITE_ENV_FILE" ]; then
    echo "Error: SITE_ENV_FILE environment variable is unset."
    echo ""
    exit 1
fi

# Check that the .env file exists
if [ ! -f "$SITE_ENV_FILE" ]; then
    echo "Error: .env file not found at path $SITE_ENV_FILE"
    echo ""
    exit 1
fi

# Load and export the environment variables
export $(grep "^MTMS_DEVICE_GENERATION=" $SITE_ENV_FILE | xargs)
export $(grep "^BITFILE_VERSION=" $SITE_ENV_FILE | xargs)
export $(grep "^RESOURCE=" $SITE_ENV_FILE | xargs)

echo "mTMS device generation: $MTMS_DEVICE_GENERATION"
echo "Bitfile version: $BITFILE_VERSION"

# Configure mTMS bridge
export BITFILE_DIRECTORY=$MTMS_ROOT/bitfiles

export BITFILE_PREFIX="NiFpga_mTMS_generation_${MTMS_DEVICE_GENERATION}_${BITFILE_VERSION}"

export BITFILE=$BITFILE_PREFIX.lvbitx
export BITFILE_SIGNATURE="$(cat $BITFILE_DIRECTORY/$BITFILE_PREFIX.signature)"

# Build mTMS bridge
cd mtms/ros2_ws
colcon build --packages-select event_interfaces mtms_device_interfaces mtms_device_bridge

# Start mTMS bridge
ros2 launch mtms_device_bridge mtms_device_bridge.launch.py log-level:=info safe-mode:=false
