#!/bin/bash

if [ -z "$PROJECT_NAME" ]; then
    echo "Error: Project name is undefined. Please use set-project script to set the project."
    exit 1
fi

# Get the service name from the first argument
SERVICE_NAME="$1"

if [ -z "$SERVICE_NAME" ]; then
    echo "Error: Service name is undefined. Please provide it as an argument to the script."
    exit 1
fi

# Allow Docker containers to connect to the host X server.
xhost +local:docker

# Set PROJECT_ENV_FILE to point to .env of the project
export PROJECT_ENV_FILE=$PROJECTS_ROOT/$PROJECT_NAME/.env

cd $MTMS_ROOT
docker-compose -f docker-compose.project.yml build $SERVICE_NAME
docker-compose -f docker-compose.project.yml up $SERVICE_NAME
