#!/bin/bash

cd $MTMS_ROOT

# Set SITE_ENV_FILE to point to .env of the site
export SITE_ENV_FILE=$MTMS_ROOT/sites/$SITE/.env

# Source the environment variables from SITE_ENV_FILE
set -a
source $SITE_ENV_FILE
set +a

# Start the containers defined in docker-compose.core.yml
docker-compose -f docker-compose.core.yml up
