#!/bin/bash

# Check that SITE is set.
if [ -z "$SITE" ]; then
    echo "Error: SITE environment variable is unset."
    echo ""
    exit 1
fi

# Set SITE_ENV_FILE to point to .env of the site
export SITE_ENV_FILE=$MTMS_ROOT/sites/$SITE/.env

# Check that the .env file exists
if [ ! -f "$SITE_ENV_FILE" ]; then
    echo "Error: .env file not found at path $SITE_ENV_FILE"
    echo ""
    exit 1
fi

# Load and export the environment variables
export $(grep "^MTMS_DEVICE_ENABLED=" $SITE_ENV_FILE | xargs)
export $(grep "^MTMS_DEVICE_GENERATION=" $SITE_ENV_FILE | xargs)
export $(grep "^BITFILE_VERSION=" $SITE_ENV_FILE | xargs)
export $(grep "^RESOURCE=" $SITE_ENV_FILE | xargs)
export $(grep "^CHANNEL_COUNT=" $SITE_ENV_FILE | xargs)

echo "mTMS device enabled: $MTMS_DEVICE_ENABLED"
echo "mTMS device generation: $MTMS_DEVICE_GENERATION"
echo "Bitfile version: $BITFILE_VERSION"
echo "Channel count: $CHANNEL_COUNT"

# Configure mTMS bridge
export BITFILE_DIRECTORY=$MTMS_ROOT/bitfiles

export BITFILE_PREFIX="NiFpga_mTMS_generation_${MTMS_DEVICE_GENERATION}_${BITFILE_VERSION}"

export BITFILE=$BITFILE_PREFIX.lvbitx
export BITFILE_SIGNATURE="$(cat $BITFILE_DIRECTORY/$BITFILE_PREFIX.signature)"

export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

# Initialize ROS
source /opt/ros/iron/setup.bash

# Build mTMS bridge
cd $MTMS_ROOT/ros2_ws

# Build all interfaces to keep native ROS2 environment up to date.
colcon build --base-paths src/interfaces

# Build mTMS device bridge.
colcon build --packages-select mtms_device_bridge

source $MTMS_ROOT/ros2_ws/install/local_setup.bash

# Start mTMS bridge
ros2 launch mtms_device_bridge mtms_device_bridge.launch.py log-level:=info safe-mode:=false enabled:=$MTMS_DEVICE_ENABLED channel-count:=$CHANNEL_COUNT
