from .Error import Error

class ChargeError(Error):
    NO_ERROR = 0
    INVALID_EXECUTION_CONDITION = 1
    INVALID_CHANNEL = 2
    INVALID_VOLTAGE = 3
    LATE = 4
    OVERLAPPING_WITH_DISCHARGING = 5
    OVERLAPPING_WITH_STIMULATION = 6
    CHARGING_FAILURE = 7
    UNKNOWN_ERROR = 8
