from .Error import Error

class DischargeError(Error):
    NO_ERROR = 0
    INVALID_EXECUTION_CONDITION = 1
    INVALID_CHANNEL = 2
    INVALID_VOLTAGE = 3
    LATE = 4
    OVERLAPPING_WITH_CHARGING = 5
    OVERLAPPING_WITH_STIMULATION = 6
    DISCHARGING_FAILURE = 7
    UNKNOWN_ERROR = 8
