from .Error import Error

class PulseError(Error):
    NO_ERROR = 0
    INVALID_EXECUTION_CONDITION = 1
    INVALID_CHANNEL = 2
    INVALID_NUMBER_OF_PIECES = 3
    INVALID_MODES = 4
    INVALID_DURATIONS = 5
    LATE = 6
    TOO_MANY_PULSES = 7
    OVERLAPPING_WITH_CHARGING = 8
    OVERLAPPING_WITH_DISCHARGING = 9
    TRIGGERING_FAILURE = 10
    UNKNOWN_ERROR = 11
