from .Error import Error

class StartupSequenceError(Error):
    NO_ERROR = 0
    UART_INITIALIZATION_FAILED = 1
    BOARD_STARTUP_FAILED = 2
    BOARD_STATUS_MESSAGE_FAILED = 3
    SAFETY_MONITOR_ERROR = 4
    DISCHARGE_CONTROLLER_ERROR = 5
    CHARGE_ERROR = 6
    SENSORBOARD_ERROR = 7
    DISCHARGE_CONTROLLER_VOLTAGE_ERROR = 8
    CHARGER_VOLTAGE_ERROR = 9
    IGBT_FEEDBACK_ERROR = 10
