# Request events from the mTMS device.
#
# Response: Boolean indicating if requesting was successful.

event_interfaces/Pulse[] pulses
event_interfaces/Charge[] charges
event_interfaces/Discharge[] discharges
event_interfaces/TriggerOut[] trigger_outs
---
bool success
