function waveform = algorithm_micropulse(obj, parameter, total_duration, mode_info)
    current_mode = mode_info.current_mode;
    position = mode_info.position;  % Flag to indicate if mode before (1), after (2), or between (3) hold phases.

    if current_mode == 'r' && position == 1
        waveform = struct( ...
            'mode', {'h', 'f', 'r'}, ...
            'duration', {parameter, obj.minimum_mode_duration, total_duration - parameter - obj.minimum_mode_duration});

    elseif current_mode == 'r' && position == 2
        waveform = struct( ...
            'mode', {'r', 'f', 'h','f','r'}, ...
            'duration', {parameter, obj.minimum_mode_duration, total_duration - (parameter + obj.minimum_mode_duration) * 2, obj.minimum_mode_duration, parameter});

    elseif current_mode == 'f' && position == 1
        waveform = struct( ...
            'mode', {'h', 'r', 'f'}, ...
            'duration', {parameter, obj.minimum_mode_duration, total_duration - parameter - obj.minimum_mode_duration});

    elseif current_mode == 'f' && position == 2
        waveform = struct( ...
            'mode', {'f', 'r', 'h','r','f'}, ...
            'duration', {parameter, obj.minimum_mode_duration, total_duration - (parameter + obj.minimum_mode_duration) * 2, obj.minimum_mode_duration, parameter});
    
    elseif current_mode == 'r' && position == 3
        waveform = struct( ...
            'mode', {'r', 'f', 'h'}, ...
            'duration', {parameter, obj.minimum_mode_duration, total_duration - parameter - obj.minimum_mode_duration});

    elseif current_mode == 'f' && position == 3
        waveform = struct( ...
            'mode', {'f', 'r', 'h'}, ...
            'duration', {parameter, obj.minimum_mode_duration, total_duration - parameter - obj.minimum_mode_duration});

    elseif current_mode == 'h'
        waveform = struct( ...
            'mode', {'h'}, ...
            'duration', {total_duration});

    elseif current_mode == 'a'
        waveform = struct( ...
            'mode', {'a'}, ...
            'duration', {total_duration});

    else
        error('Invalid mode: %s', current_mode);
    end
end
