function initial_state = generate_initial_state(obj, voltage)
    initial_state = struct(...
        'V_c', voltage, ...
        'V_s1', 0, ...
        'V_s2', voltage, ...
        'V_s3', 0, ...
        'V_s4', voltage, ...
        'I_coil', 0, ...
        'I_tw', 0, ...
        'I_bar_U', 0, ...
        'I_bar_L', 0, ...
        'I_z_L', 0, ...
        'I_z_R', 0);
end
