# build environment
FROM node:16.13.2 as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY /front/package.json ./
COPY /front/yarn.lock ./
RUN yarn install --silent
RUN yarn global add react-scripts@5.0.0 --silent
COPY /front/ /app
RUN yarn run build

# production environment
FROM nginx:1.13.9-alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY /front/nginx-default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
