#!/bin/bash

# Build the ROS2 workspace and generate the MATLAB message files.
#
# This script is intended to be run on the mTMS computer when ROS2 messages have been added or modified.

# Define the text formatting codes
BOLD=$(tput bold)
UNDERLINE=$(tput smul)
RESET=$(tput sgr0)

echo "  • ${BOLD}Building the MATLAB interfaces...${RESET}"

# Create a temporary directory for all the interfaces
mkdir -p $MTMS_ROOT/ros2_ws/src/temp_interfaces
ln -s $MTMS_ROOT/ros2_ws/src/shared_packages/interfaces/* $MTMS_ROOT/ros2_ws/src/temp_interfaces/
ln -s $MTMS_ROOT/ros2_ws/src/mtms_packages/interfaces/* $MTMS_ROOT/ros2_ws/src/temp_interfaces/

# Generate the MATLAB message files
matlab -nodisplay -nosplash -nodesktop -r " \
ros2genmsg('/home/mtms/mtms/ros2_ws/src/temp_interfaces', 'CreateShareableFile', true, 'BuildConfiguration', 'fasterruns'); \
exit;"

if [ $? -ne 0 ]; then
    echo "Error: MATLAB failed to generate the message files."

    # Remove the temporary directory
    rm -rf $MTMS_ROOT/ros2_ws/src/temp_interfaces

    exit 1
fi

# Move the generated MATLAB message files to the API directory
mv "$MTMS_ROOT/ros2_ws/src/temp_interfaces/matlab_msg_gen.zip" "$MTMS_ROOT/api/matlab/"

# Remove the temporary directory
rm -rf $MTMS_ROOT/ros2_ws/src/temp_interfaces

echo "  • ${BOLD}Registering the MATLAB interfaces...${RESET}"

# Register messages in MATLAB
matlab -nodisplay -nosplash -nodesktop -r " \
ros2RegisterMessages('/home/mtms/mtms/api/matlab'); \
exit;"

# Delete the unneeded package directories, generated when running ros2RegisterMessages in MATLAB.
rm -rf $MTMS_ROOT/api/matlab/*interfaces
rm -rf $MTMS_ROOT/api/matlab/*msgs
rm -rf $MTMS_ROOT/api/matlab/*services

echo "Done."
echo ""
echo "To commit the built MATLAB message files, run the following command:"
echo ""
echo "  git commit api/matlab/matlab_msg_gen.zip -m \"UPD: ROS interfaces in MATLAB API\""
echo ""
