#!/bin/bash

# Build the ROS2 workspace and generate the MATLAB message files.
#
# This script is intended to be run on the mTMS computer when ROS2 messages have been added or modified.

# Define the text formatting codes
BOLD=$(tput bold)
UNDERLINE=$(tput smul)
RESET=$(tput sgr0)

echo "  • ${BOLD}Building the MATLAB interfaces...${RESET}"

# Create a temporary directory for all the interfaces
TEMP_INTERFACES_DIR=$(mktemp -d /tmp/mtms-matlab-interfaces.XXXXXX)
cleanup() {
    rm -rf "$TEMP_INTERFACES_DIR"
}
trap cleanup EXIT

ln -sf "$MTMS_ROOT"/ros2_ws/src/shared_packages/interfaces/* "$TEMP_INTERFACES_DIR"/
ln -sf "$MTMS_ROOT"/ros2_ws/src/mtms_packages/interfaces/* "$TEMP_INTERFACES_DIR"/

# Generate the MATLAB message files
matlab -nodisplay -nosplash -nodesktop -r " \
ros2genmsg('$TEMP_INTERFACES_DIR', 'CreateShareableFile', true, 'BuildConfiguration', 'fasterruns'); \
exit;"

if [ $? -ne 0 ]; then
    echo "Error: MATLAB failed to generate the message files."
    exit 1
fi

# Move the generated MATLAB message files to the API directory
mv "$TEMP_INTERFACES_DIR/matlab_msg_gen.zip" "$MTMS_ROOT/api/matlab/"

echo "Done."
echo ""
echo "To commit the built MATLAB message files, run the following command:"
echo ""
echo "  git commit api/matlab/matlab_msg_gen.zip -m \"UPD: ROS interfaces in MATLAB API\""
echo ""
