#!/bin/bash

# Define the text formatting codes
BOLD=$(tput bold)
UNDERLINE=$(tput smul)
RESET=$(tput sgr0)

# Ensure that $MTMS_ROOT is set
if [ -z "$MTMS_ROOT" ]; then
    echo "Error: \$MTMS_ROOT is not set."
    echo "Please set \$MTMS_ROOT to the root directory of the mTMS repository."
    exit 1
fi

# Preserve caller's working directory since this script is sourced.
ORIGINAL_PWD=$(pwd)

echo ""
echo "Building the ROS workspace:"

# Source ROS
source /opt/ros/jazzy/setup.bash

# Build interfaces
echo "  • ${BOLD}Building interfaces...${RESET}"

cd $MTMS_ROOT/ros2_ws
colcon build --base-paths src/interfaces src/realtime_utils

# Build mTMS device bridge
echo "  • ${BOLD}Building mTMS device bridge...${RESET}"

colcon build --packages-select mtms_device_bridge

# Source the workspace
source $MTMS_ROOT/install/local_setup.bash

# Restore caller's working directory.
cd "$ORIGINAL_PWD"

echo ""
echo "Done."
echo ""
