#!/bin/bash

# Define the text formatting codes
BOLD=$(tput bold)
UNDERLINE=$(tput smul)
RESET=$(tput sgr0)

echo ""
echo "Building the ROS workspace:"

# Source ROS
source /opt/ros/iron/setup.bash

# Build interfaces
echo "  • ${BOLD}Building interfaces...${RESET}"

cd $MTMS_ROOT/ros2_ws
colcon build --base-paths src/shared_packages/interfaces src/mtms_packages/interfaces

# Build mTMS device bridge
echo "  • ${BOLD}Building mTMS device bridge...${RESET}"

colcon build --packages-select mtms_device_bridge

# Source the workspace
source $MTMS_ROOT/ros2_ws/install/local_setup.bash

echo ""
echo "Done."
echo ""
