#!/bin/bash
set -e

if [ -z "$1" ]; then
    echo "Please provide the target site as an argument."
    exit 1
fi

# Set target_site
export target_site=$1

# Ensure that MATLAB is installed
if ! which matlab > /dev/null; then
    echo "MATLAB is not installed or not in the PATH."
    echo "Please install MATLAB and ensure that the executable is in the PATH."
    exit 1
fi

# Check if Ansible is installed
if ! command -v ansible-playbook &> /dev/null; then
    echo "Ansible is not installed. Installing Ansible..."
    sudo apt update
    sudo apt install -y software-properties-common
    sudo add-apt-repository --yes --update ppa:ansible/ansible
    sudo apt install -y ansible
fi

# Run the Ansible playbook
echo "Installing required Ansible collections..."
ansible-galaxy collection install -r ansible/requirements.yml

# Prompt for sudo password once
read -s -p "Enter sudo password: " SUDO_PASS
echo ""
# Run the Docker installation playbook
ANSIBLE_BECOME_PASS=$SUDO_PASS ansible-playbook -i 'localhost,' ansible/install-docker.yml --extra-vars "ansible_become_password=$SUDO_PASS"
# Run the Docker installation playbook
ANSIBLE_BECOME_PASS=$SUDO_PASS ansible-playbook -i 'localhost,' ansible/install-ros.yml --extra-vars "ansible_become_password=$SUDO_PASS"
# Run the mTMS installation playbook
ansible-playbook -i 'localhost,' ansible/install-mtms.yml --ask-become-pass -e target_site=$target_site

set +e  # Allow sourcing of .bash_env before ROS workspace is built
source $HOME/.bash_env
set -e

# Build the ROS workspace
source $MTMS_ROOT/scripts/build-mtms-ros-workspace

# Source again after building the ROS workspace
source $HOME/.bash_env

# Build documentation
source scripts/build-docs

# Build MATLAB ROS interfaces if requested
echo "Do you want to build the MATLAB ROS interfaces? (Y/n) (Note: This takes a few minutes to complete.)"
read -r response

if [ "$response" != "n" ]; then
    source scripts/build-mtms-matlab
else
    echo "Skipping MATLAB ROS interfaces build."
fi

# Register MATLAB ROS interfaces
source scripts/register-mtms-matlab

# Build mTMS containers
source scripts/build-mtms

echo "Done."
echo ""
echo "Reboot your computer to complete the installation."
echo ""
