#!/bin/bash

# Build the ROS2 workspace and generate the MATLAB message files.
#
# This script is intended to be run on the mTMS computer when ROS2 messages have been added or modified.

# Define the text formatting codes
BOLD=$(tput bold)
UNDERLINE=$(tput smul)
RESET=$(tput sgr0)

# Create a temporary directory for all the interfaces
mkdir -p /home/mtms/mtms/ros2_ws/src/temp_interfaces
ln -s /home/mtms/mtms/ros2_ws/src/shared_packages/interfaces/* /home/mtms/mtms/ros2_ws/src/temp_interfaces/
ln -s /home/mtms/mtms/ros2_ws/src/mtms_packages/interfaces/* /home/mtms/mtms/ros2_ws/src/temp_interfaces/

# Generate the MATLAB message files
matlab -nodisplay -nosplash -nodesktop -r " \
ros2genmsg('/home/mtms/mtms/ros2_ws/src/temp_interfaces', 'CreateShareableFile', true, 'BuildConfiguration', 'fasterruns'); \
exit;"

# Check if the .zip file exists and then move it
if [ -f "$MTMS_ROOT/ros2_ws/src/temp_interfaces/matlab_msg_gen.zip" ]; then
    mv "$MTMS_ROOT/ros2_ws/src/temp_interfaces/matlab_msg_gen.zip" "$MTMS_ROOT/api/matlab/"
else
    echo "matlab_msg_gen.zip does not exist."
fi

# Delete the matlab_msg_gen directory
if [ -d "$MTMS_ROOT/ros2_ws/src/temp_interfaces/matlab_msg_gen" ]; then
    rm -rf "$MTMS_ROOT/ros2_ws/src/temp_interfaces/matlab_msg_gen"
else
    echo "matlab_msg_gen directory does not exist."
fi

# Remove the temporary directory
rm -rf /home/mtms/mtms/ros2_ws/src/temp_interfaces

echo "Done."
echo ""
echo "• To register the MATLAB message files with MATLAB, run the following command:"
echo ""
echo "${BOLD}matlab-register${RESET}"
echo ""
echo "• To commit the built MATLAB message files, run the following command:"
echo ""
echo "${BOLD}matlab-commit${RESET}"
echo ""
