#!/bin/bash

echo "  • ${BOLD}Registering the MATLAB interfaces...${RESET}"

# Register messages in MATLAB
matlab -nodisplay -nosplash -nodesktop -r " \
ros2RegisterMessages('/home/mtms/mtms/api/matlab'); \
exit;"

# Delete the unneeded package directories, generated when running ros2RegisterMessages in MATLAB.
rm -rf $MTMS_ROOT/api/matlab/*interfaces
rm -rf $MTMS_ROOT/api/matlab/*msgs
rm -rf $MTMS_ROOT/api/matlab/*services

echo "Done."
echo ""
