#!/bin/bash

# Define the text formatting codes
BOLD=$(tput bold)
UNDERLINE=$(tput smul)
RESET=$(tput sgr0)

# Stop session if active.
source $MTMS_ROOT/scripts/stop-session

# Restart core containers.
echo "${BOLD}Restarting...${RESET}"

sudo systemctl restart mtms-bridge

echo "${BOLD}Done.${RESET}"
