#!/bin/bash

cd $MTMS_ROOT

# Set ENV_FILE to point to .env of the site
export ENV_FILE=$MTMS_ROOT/sites/$SITE/.env

# Source the environment variables from ENV_FILE
set -a
source $ENV_FILE
set +a

# Start containers
docker-compose up
