#!/bin/bash

cd $MTMS_ROOT

# Set SITE_ENV_FILE to point to .env of the site
export SITE_ENV_FILE=$MTMS_ROOT/sites/$SITE/.env

# Source the environment variables from SITE_ENV_FILE
set -a
source $SITE_ENV_FILE
set +a

# Start containers
docker-compose up
