#!/bin/bash

cd $MTMS_ROOT

# Set MTMS_ENV_FILE to point to .env of the site
export MTMS_ENV_FILE=$MTMS_ROOT/sites/$SITE/.env

# Source the environment variables from MTMS_ENV_FILE
set -a
source $MTMS_ENV_FILE
set +a

# Start containers
docker-compose up
