#!/bin/bash

cd $MTMS_ROOT

# Set ENV_FILE to point to .env of the site
export ENV_FILE=$MTMS_ROOT/sites/$SITE/.env

# Source the environment variables from ENV_FILE
set -a
source $ENV_FILE
set +a

# Stop the containers defined in docker-compose.yml
docker-compose -f docker-compose.yml down --remove-orphans
