# Request events from the mTMS device.
#
# Response: Boolean indicating if requesting was successful.

event_msgs/Pulse[] pulses
event_msgs/Charge[] charges
event_msgs/Discharge[] discharges
event_msgs/TriggerOut[] trigger_outs
---
bool success
