# ROS service for approximating waveform of a lower target voltage using a higher actual voltage.

uint16 actual_voltage
uint16 target_voltage
event_interfaces/Waveform waveform
uint8 coil_number
---
bool success
event_interfaces/Waveform approximated_waveform
