#!/bin/bash

set -e
set -o pipefail

bash ./clean.sh

find ../codegen -name "*.h"   -not \( -path "*/interface/*" -prune \) -not \( -path "*/examples/*" -prune \) -exec cp "{}" . \;
find ../codegen -name "*.cpp" -not \( -path "*/interface/*" -prune \) -not \( -path "*/examples/*" -prune \) -exec cp "{}" . \;
find ../codegen -name "*.c" -not \( -path "*/interface/*" -prune \) -not \( -path "*/examples/*" -prune \) -exec cp "{}" . \;

# HACK: We need to make the methods generated by MATLAB for the class MatlabProcessor virtual, and also make the class
# extend MatlabProcessorInterface
PROCESSOR_H=MatlabProcessor.h
sed -i -e 's/MatlabProcessor \*init/virtual MatlabProcessor \*init/' $PROCESSOR_H
# double space to not rename create_command
sed -i -e 's/  void/virtual void/' $PROCESSOR_H
sed -i -e 's/class MatlabProcessor/class MatlabProcessor : public MatlabProcessorInterface/' $PROCESSOR_H
sed -i -e '/Include files/a #include "matlab_processor_interface.h"' $PROCESSOR_H
cmake .
make all -j$(nproc)

