name: Build
on:
  pull_request:

jobs:
  test:
    name: Build ROS packages
    runs-on: ubuntu-20.04
    env:
      COMPOSE_FILE: .ci/docker-compose.build.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Docker images
        run: docker-compose build

      - name: Create docker-compose logs
        run: docker-compose logs > docker-compose.log
        if: failure()

      - name: Upload docker-compose logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: docker-logs
          path: docker-compose.log
