name: Update docs

on: [pull_request, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Clone the repository for the docs
        run: cd docs && git clone https://github.com/connect2brain/project-louhi-docs public

      - name: Install Node dependencies
        run: cd docs && npm install @asyncapi/generator openapi-sampler

      - name: Install Python dependencies
        run: cd docs && sudo pip install pip-tools && pip-compile requirements.in && sudo pip install -r requirements.txt

      - name: Set up Git identity
        run: git config --global user.email "" && git config --global user.name "project-louhi"

      # Runs a single command using the runners shell
      - name: Build and deploy the documentation
        run: cd docs && sh deploy.sh
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
