name: CI
on:
  pull_request:
  push:

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-20.04
    env:
      COMPOSE_FILE: .ci/docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker images
        run: docker-compose build

      - name: Start containers
        run: docker-compose up -d

      - name: Print pwd
        run: pwd

      - name: print ls
        run: ls -la

      - name: Change directory
        run: cd front

      - name: print ls again
        run: ls -la

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
