FROM osrf/ros:iron-desktop as builder

SHELL ["/bin/bash", "-c"]


WORKDIR /app
COPY ros2_ws/src/other/stimulation_allower ros2_ws/src/other/stimulation_allower/
COPY ros2_ws/src/interfaces/neuronavigation_interfaces ros2_ws/src/interfaces/neuronavigation_interfaces/
COPY ros2_ws/src/interfaces/mtms_device_interfaces ros2_ws/src/interfaces/mtms_device_interfaces/

# Build ROS packages

WORKDIR /app/ros2_ws
RUN source /opt/ros/iron/setup.bash && \
    colcon build

# Production environment
FROM osrf/ros:iron-desktop

# Install dependencies
WORKDIR /build

RUN apt-get update

RUN apt-get install -y \
    dos2unix

# Copy ROS workspace

WORKDIR /app
COPY --from=builder /app/ros2_ws/build/ ros2_ws/build/
COPY --from=builder /app/ros2_ws/install/ ros2_ws/install/

# Copy entrypoint

COPY ros2_ws/src/other/stimulation_allower/ros_entrypoint.sh .
RUN dos2unix ros_entrypoint.sh
RUN chmod +x ros_entrypoint.sh

ENTRYPOINT ["./ros_entrypoint.sh"]
